### ISSUE TITLE
CRC link not working

### ISSUE THREAD

**Issue by mkinnaman** [caravagn/mobster_supp_data#1]
Hi Giulio,

I am having a little trouble getting out of the gates here. I have multiregion WGS data I would like to run through the mobster pipeline but its not clear to me what type of input is needed. I was hoping the CRC vignette would make things clear but it appears that the links for it are not working - getting a 404 not found error. Appreciate your help.

Thanks,
Michael

**Comment by caravagn** [comment]
Hey @mkinnaman apologise yeah something went wrong and basically I had lost the CRC folder (which was supposed indeed to be in this repo). 

I just pushed that now: https://github.com/caravagn/mobster_supp_data/commit/9298d8472e2539a68d517fe557316c16ddd1537c

I think the NG version online, which contains a dump of the repo, should have had the folder.
